// src/ai/flows/generate-response-with-tools.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a response using the Gemini model, 
 * incorporating memory, tools, and logging.
 *
 * @exports generateResponseWithTools - A function that orchestrates the response generation process.
 * @exports GenerateResponseWithToolsInput - The input type for the generateResponseWithTools function.
 * @exports GenerateResponseWithToolsOutput - The output type for the generateResponseWithTools function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Define schemas for input and output types
const GenerateResponseWithToolsInputSchema = z.object({
  sessionId: z.string().describe('The session ID for the conversation.'),
  userMessage: z.string().describe('The user message to be processed.'),
  memoryFacts: z.array(z.string()).describe('The memory facts associated with the session.'),
  toolDescriptors: z.array(z.object({
    name: z.string(),
    description: z.string(),
    inputSchema: z.any(),
    outputSchema: z.any(),
  })).optional().describe('The tool descriptors available for the agent to use.'),
});
export type GenerateResponseWithToolsInput = z.infer<typeof GenerateResponseWithToolsInputSchema>;

const GenerateResponseWithToolsOutputSchema = z.object({
  finalResponse: z.string().describe('The final response generated by the model.'),
  toolCalls: z.array(z.object({
    name: z.string(),
    arguments: z.record(z.any()),
  })).optional().describe('The tool calls requested by the model.'),
});
export type GenerateResponseWithToolsOutput = z.infer<typeof GenerateResponseWithToolsOutputSchema>;

// Exported function to call the flow
export async function generateResponseWithTools(input: GenerateResponseWithToolsInput): Promise<GenerateResponseWithToolsOutput> {
  return generateResponseWithToolsFlow(input);
}

// Define the prompt
const generateResponsePrompt = ai.definePrompt({
  name: 'generateResponsePrompt',
  input: { schema: GenerateResponseWithToolsInputSchema },
  output: { schema: GenerateResponseWithToolsOutputSchema },
  prompt: `You are a helpful assistant that can use tools to answer the user's questions.

  You have access to the following tools:
  {{#each toolDescriptors}}
    - {{name}}: {{description}}
  {{/each}}

  You should use the tools if the user's question requires it.

  Here are some memory facts about the user's session:
  {{#each memoryFacts}}
    - {{this}}
  {{/each}}

  Now, respond to the following user message: {{{userMessage}}}

  Remember to think step by step, and write facts to memory as you learn new things.
  If the user asks you to do something (e.g. add a todo), use a tool to do it.
  `, //End prompt
});

// Define the flow
const generateResponseWithToolsFlow = ai.defineFlow(
  {
    name: 'generateResponseWithToolsFlow',
    inputSchema: GenerateResponseWithToolsInputSchema,
    outputSchema: GenerateResponseWithToolsOutputSchema,
  },
  async (input) => {
    const { output } = await generateResponsePrompt(input);
    return output!;
  }
);
