'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a simple response using the Gemini model.
 *
 * @exports generateResponse - A function that generates a direct response to a user's message.
 * @exports GenerateResponseInput - The input type for the generateResponse function.
 * @exports GenerateResponseOutput - The output type for the generateResponse function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Define schemas for input and output types
const GenerateResponseInputSchema = z.object({
  userMessage: z.string().describe('The user message to be processed.'),
});
export type GenerateResponseInput = z.infer<typeof GenerateResponseInputSchema>;

const GenerateResponseOutputSchema = z.object({
  response: z.string().describe('The response generated by the model.'),
});
export type GenerateResponseOutput = z.infer<typeof GenerateResponseOutputSchema>;

// Exported function to call the flow
export async function generateResponse(input: GenerateResponseInput): Promise<GenerateResponseOutput> {
  return generateResponseFlow(input);
}

// Define the prompt
const generateResponsePrompt = ai.definePrompt({
  name: 'generateResponsePrompt',
  input: { schema: GenerateResponseInputSchema },
  output: { schema: GenerateResponseOutputSchema },
  prompt: `You are a helpful assistant. Provide a direct, conversational answer to the user's message.

User's message: {{{userMessage}}}
`,
});

// Define the flow
const generateResponseFlow = ai.defineFlow(
  {
    name: 'generateResponseFlow',
    inputSchema: GenerateResponseInputSchema,
    outputSchema: GenerateResponseOutputSchema,
  },
  async (input) => {
    const { output } = await generateResponsePrompt(input);
    return output!;
  }
);
