
// src/ai/flows/generate-response-with-tools.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a response using the Gemini model, 
 * incorporating memory, tools, and logging.
 *
 * @exports generateResponseWithTools - A function that orchestrates the response generation process.
 * @exports GenerateResponseWithToolsInput - The input type for the generateResponseWithTools function.
 * @exports GenerateResponseWithToolsOutput - The output type for the generateResponseWithTools function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Define schemas for input and output types
const GenerateResponseWithToolsInputSchema = z.object({
  sessionId: z.string().describe('The session ID for the conversation.'),
  userMessage: z.string().describe('The user message to be processed.'),
  memoryFacts: z.array(z.string()).describe('The memory facts associated with the session.'),
  toolDescriptors: z.array(z.object({
    name: z.string(),
    description: z.string(),
    inputSchema: z.any(),
    outputSchema: z.any(),
  })).optional().describe('The tool descriptors available for the agent to use.'),
});
export type GenerateResponseWithToolsInput = z.infer<typeof GenerateResponseWithToolsInputSchema>;

const GenerateResponseWithToolsOutputSchema = z.object({
  finalResponse: z.string().describe('The final response generated by the model.'),
  toolCalls: z.array(z.object({
    name: z.string(),
    arguments: z.record(z.any()),
  })).optional().describe('The tool calls requested by the model.'),
});
export type GenerateResponseWithToolsOutput = z.infer<typeof GenerateResponseWithToolsOutputSchema>;

// Exported function to call the flow
export async function generateResponseWithTools(input: GenerateResponseWithToolsInput): Promise<GenerateResponseWithToolsOutput> {
  return generateResponseWithToolsFlow(input);
}

// Define the prompt
const generateResponsePrompt = ai.definePrompt({
  name: 'generateResponsePrompt',
  input: { schema: GenerateResponseWithToolsInputSchema },
  output: { schema: GenerateResponseWithToolsOutputSchema },
  prompt: `You are a helpful assistant. Your goal is to provide a useful response to the user's message.

You have access to the following tools:
{{#if toolDescriptors}}
{{#each toolDescriptors}}
- {{name}}: {{description}}
{{/each}}
{{else}}
No tools available.
{{/if}}

You also have access to the following memory facts from the user's session:
{{#if memoryFacts}}
{{#each memoryFacts}}
- {{this}}
{{/each}}
{{/if}}

Here is the user's message: {{{userMessage}}}

Follow these instructions:
1.  Analyze the user's message.
2.  If the message requires an action that a tool can perform, you MUST use the appropriate tool. Your response should consist ONLY of the tool call.
3.  If the message is a greeting, question, or statement that does not require a tool, provide a direct, conversational answer in the 'finalResponse' field.
4.  If you do not use a tool, your response MUST include a 'finalResponse' field.
`,
});

// Define the flow
const generateResponseWithToolsFlow = ai.defineFlow(
  {
    name: 'generateResponseWithToolsFlow',
    inputSchema: GenerateResponseWithToolsInputSchema,
    outputSchema: GenerateResponseWithToolsOutputSchema,
  },
  async (input) => {
    const { output } = await generateResponsePrompt(input);
    return output!;
  }
);
