// src/ai/flows/generate-response-with-tools.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a response using the Gemini model, 
 * incorporating memory, tools, and logging.
 *
 * @exports generateResponseWithTools - A function that orchestrates the response generation process.
 * @exports GenerateResponseWithToolsInput - The input type for the generateResponseWithTools function.
 * @exports GenerateResponseWithToolsOutput - The output type for the generateResponseWithTools function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Define schemas for input and output types
const GenerateResponseWithToolsInputSchema = z.object({
  sessionId: z.string().describe('The session ID for the conversation.'),
  userMessage: z.string().describe('The user message to be processed.'),
  memoryFacts: z.array(z.string()).describe('The memory facts associated with the session.'),
  toolDescriptors: z.array(z.object({
    name: z.string(),
    description: z.string(),
    inputSchema: z.any(),
    outputSchema: z.any(),
  })).optional().describe('The tool descriptors available for the agent to use.'),
});
export type GenerateResponseWithToolsInput = z.infer<typeof GenerateResponseWithToolsInputSchema>;

const GenerateResponseWithToolsOutputSchema = z.object({
  finalResponse: z.string().describe('The final response generated by the model.'),
  toolCalls: z.array(z.object({
    name: z.string(),
    arguments: z.record(z.any()),
  })).optional().describe('The tool calls requested by the model.'),
});
export type GenerateResponseWithToolsOutput = z.infer<typeof GenerateResponseWithToolsOutputSchema>;

// Exported function to call the flow
export async function generateResponseWithTools(input: GenerateResponseWithToolsInput): Promise<GenerateResponseWithToolsOutput> {
  return generateResponseWithToolsFlow(input);
}

// Define the prompt
const generateResponsePrompt = ai.definePrompt({
  name: 'generateResponsePrompt',
  input: { schema: GenerateResponseWithToolsInputSchema },
  output: { schema: GenerateResponseWithToolsOutputSchema },
  prompt: `You are a helpful assistant. Your goal is to provide a useful response to the user's message.

You have access to the following tools:
{{#each toolDescriptors}}
- {{name}}: {{description}}
{{/each}}

You also have access to the following memory facts from the user's session:
{{#each memoryFacts}}
- {{this}}
{{/each}}

Here is the user's message: {{{userMessage}}}

Please follow these instructions:
1.  If the user's message is a simple greeting or question (e.g., "hello", "how are you?"), provide a friendly, conversational response.
2.  If the user's message requires information or an action that a tool can provide, you MUST use the appropriate tool.
3.  If the user's message does not require a tool, provide a helpful response based on the conversation history and memory facts.
4.  Your final response should be clear, concise, and directly address the user's message.
`, //End prompt
});

// Define the flow
const generateResponseWithToolsFlow = ai.defineFlow(
  {
    name: 'generateResponseWithToolsFlow',
    inputSchema: GenerateResponseWithToolsInputSchema,
    outputSchema: GenerateResponseWithToolsOutputSchema,
  },
  async (input) => {
    const { output } = await generateResponsePrompt(input);
    return output!;
  }
);
